version: '3.7'

services:
  document-control-backend:
    restart: unless-stopped
    container_name: document-control-backend
    build:
      context: .
      target: development
    command: sh /app/entrypoint.sh
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - document-control-postgres
    networks:
      - document-control-network

  document-control-postgres:
    container_name: document-control-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - document-control-network

networks:
  document-control-network:
    external: true

volumes:
  pgdata: